name: Node.js CI

on:
  push:
    branches: [ master ]
    paths: [ 'README.md' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm start
    - run: npm run generate-concepts
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: bhaumik55231
        author_email: bhaumik55231@gmail.com
        message: "generating new file"
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
